### ISSUE TITLE
Filter cities by country

### ISSUE THREAD

**Issue by joseluizcoe** [elyase/geotext#6]
In some cases we need to extract cities from specific country. What do you think about implement it @elyase?

**Comment by elyase** [comment]
You mean like preconditioning the cities to belong to a specific country? Can you give an example of the expected behaviour you mean?

**Comment by joseluizcoe** [comment]
Using this text:

> As capitais da região sul são: Porto Alegre no Rio Grande do Sul, Floripa em Santa Catarina,  Curitiba no Paraná o Texas não faz parte do sul do brasil"""

In Brazil, we expect only bazillian cities: 
``` ['Porto Alegre', 'Rio Grande', 'Curitiba'] ```

But GeoText return the list above and this cities bellow:
- Paraná (MX)
- Santa Catarina (AR)
- Texas (US)

**Comment by elyase** [comment]
That looks like a useful feature, thanks for the suggestions. Do you have a specific API in mind? This are two alternatives that occur to me:

```python
places = Geotext(text)
brazilian_cities = [each.name for each in places if each.country == 'Brazil' and each.is_city ]
```

or 
```python
places = Geotext(text, country='Brazil')
places.cities
```

The first if more general and can be applied to more use cases. The second is easier to use but more restricted in its applicability. May be both should be there? Any thoughts?

**Comment by joseluizcoe** [comment]
Hi, @elyase. The second alternative it's ok for me. 

This works for me:
```
result = GeoText(text)
cities = [city for city in result.cities if result.index[1][city.lower()] == 'BR']
```
But... i think could be a good feature.

For now, i think you can close this issue. :)

**Comment by elyase** [comment]
great that you found a workaround, I will leave it open and come back to it when I have a chance.

**Comment by elyase** [comment]
should be implemented in master:

```bash
pip install https://github.com/elyase/geotext/archive/master.zip
```
